### PR TITLE
Webpack

### PR DESCRIPTION
**Pull request by rposborne**
This switches our build process from grunt to webpack 2.  It makes the appropriate tweaks for it to run in production.

### CODE REVIEW

**Comment by rposborne** [comment]
[Refactor to use es6 modules](https://trello.com/c/ghlip1pz/27-refactor-to-use-es6-modules)

**Review by mattgrosso — APPROVED** [review]
It seems like this adds webpack and also tweaks the react components to better use export and import, yeah?

**Comment by mattgrosso** [comment]
:shipit:

**Comment by rposborne** [comment]
My understanding is that webpack wraps every file in an iffe, so at any point, you want to use something you need to import it (unless it's in the global scope).

**Pull request merged**
